### ISSUE TITLE
Obsolete program? Playback Faster is not working.

### ISSUE THREAD

**Issue by mmt999** [RMPR/atbswp#81] opened 2022-02-18 10:58 UTC
When you record a task is useful to have a play faster button, as the idea of the recorder is to make work simple,

The playback fast button is not working.

I dont understand if this program is obsolete as i also see open issues from more than 2 year ago related to this topic,

Let us know if you arent working on this more, 

Thanks in advance,

**Comment by RMPR** [comment] 2022-02-22 12:35
I will close this issue as it's a duplicate of a previous, open one. https://github.com/RMPR/atbswp/issues/66
This is a well-known issue that will be addressed when I have the bandwidth to do so. Basically right now I can speed up the mouse replay but haven't figured out a way to do the same with the keyboard, hence the "help wanted" label, showing that I am not against a PR.

**Closed by RMPR** 2022-02-22 12:35 UTC
