### ISSUE TITLE
cant run recording as separate script in Debian 10 xfce

### ISSUE THREAD

**Issue by AgentZoy** [RMPR/atbswp#58] opened 2021-05-11 14:41 UTC
I recorded some actions all works good
Saved to file using button save to exec
after that I did chmod +x to record.pyc
run it from terminal ./record.pyc
got error
./capture.pyc: line 1: $'B\r\r': command not found
./capture.pyc: line 2: unexpected EOF while looking for matching ``'
./capture.pyc: line 8: syntax error: unexpected end of file
I want to run capture as separate script

**Comment by AgentZoy** [comment] 2021-05-11 14:47
I Understand how to do it from previous issues

**Comment by RMPR** [comment] 2021-05-12 08:55
Hi, thanks for reporting. I don't get what you're saying in your second message. Did you manage to solve the issue?

**Comment by AgentZoy** [comment] 2021-05-12 08:57
yes I Understand how to deal Need to run pyc file with python command

**Comment by RMPR** [comment] 2021-05-12 09:47
Great, I'll now close the issue since the problem is solved.

**Closed** 2021-05-12 09:47 UTC
